[package]
name = "x2clip-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
arboard = "3.6"
rusqlite = { version = "0.32", features = ["bundled"] }
sha2 = "0.10"
dirs = "5"
dryoc = "1.0.0"
rusty-s3 = "0.10.2"
toml = "1.1.4"
serde_json = "1.0.151"
ulid = "3.0.0"
hex = "0.4.3"
serde = { version = "1.0.229", features = ["derive"] }
ureq = "3.4.0"

[dev-dependencies]
serde_json = "1.0.151"
